# Generated by Django 2.2.2 on 2019-06-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdiagnoses',
            name='doctors_comment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientdiagnoses',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientdiagnoses',
            name='model_diagnosis',
            field=models.CharField(choices=[('DME', 'Diabetic macular edema'), ('AMD', 'Age-related macular degeneration'), ('NORMAL', 'Normal')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('SUPERUSER', 'SuperUSer')], max_length=6),
        ),
    ]
