# Generated by Django 2.2.2 on 2019-06-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdiagnoses',
            name='confidence_factor',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientdiagnoses',
            name='model_diagnosis',
            field=models.CharField(choices=[('DME', 'Diabetic macular edema'), ('AMD', 'Age-related macular degeneration'), ('NORMAL', 'Normal')], default='', max_length=7, null=True),
        ),
    ]
